# Site settings ...
uri: thereblight.github.io
url: https://thereblight.github.io
name: Jaehwan Oh
title: 시킨 건 곧잘 한다
email: thereblight@zoho.com
author: 재환
baseurl: ""
keywords: ""
description: ""
social_username: thereblight

# Build settings ...
sass:
  style: compressed
markdown: kramdown
encoding: "utf-8"
paginate: 5
permalink: /post/:year/:month/:day/:title
paginate_path: "/page/:num/"

# Plugins ...
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
