# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 목록_오재환
email: ilovesleepgm@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  오재환의 작업 목록과 설명
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thereblight.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
# theme: jekyll-theme-minimal
remote_theme: riggraz/no-style-please
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# theme config
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "목록_오재환" # customize text for homepage link in post layout
  date_format: "%Y" # customize how date is formatted
  show_description: false # show blog description in home page
  
# Additional info for SEO

social:
  name: 오재환
  links:
    - https://www.youtube.com/@jhwan_music

locale: ko_KR

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
